### ISSUE TITLE
Chromium can't talk to UPower

### ISSUE THREAD

**Issue by gasinvein** [flathub/org.chromium.Chromium#10]
That's because UPower resides on _system_ bus, while `--talk-name=org.freedesktop.UPower` allows name on _session_ bus.
`--system-talk-name=org.freedesktop.UPower` should be used instead.

**Comment by Erick555** [comment]
Did you mean `--system-talk-name=org.freedesktop.UPower`?

**Comment by gasinvein** [comment]
@Erick555 Yes
