### ISSUE TITLE
Requires flatpak version 1.8.2

### ISSUE THREAD

**Issue by vcarceler** [flathub/org.chromium.Chromium#102]
Hello,

Ubuntu 20.04LTS packages flatpak 1.6.5 but org.chromium.Chromium requires flatpak 1.8.2.

We are a school with over 700 computers with ubuntu 20.04LTS and we are very happy with flatpak apps but it's the first time we found flatpak app that requires flatpak 1.8.2.

Would it be possible to work with flatpak 1.6.5?

**Comment by Erick555** [comment]
No, this flatpak can't work without 1.8.x. You may follow instructions from [flathub](https://flatpak.org/setup/Ubuntu/) in order to upgrade flatpak on ubuntu.
