### ISSUE TITLE
Make Vaapi work with (X)Wayland

### ISSUE THREAD

**Issue by Esokrates** [flathub/org.chromium.Chromium#103]
On my Intel Tigerlake System, Vaapi does not work in a Gnome-Wayland Session.
When starting chromium with 
```
flatpak run org.chromium.Chromium --use-gl=egl
```
I get the following:
```
[162:162:0502/235220.202979:ERROR:gl_implementation.cc(285)] Failed to load /app/chromium/swiftshader/libGLESv2.so: /app/chromium/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[162:162:0502/235220.203954:ERROR:viz_main_impl.cc(150)] Exiting GPU process due to errors during initialization
[169:169:0502/235220.210092:ERROR:gpu_init.cc(426)] Passthrough is not supported, GL is disabled
```
When starting chromium with
```
flatpak run org.chromium.Chromium --enable-features=UseOzonePlatform --ozone-platform=wayland
```
I see the following:
```
[44:44:0502/235901.327167:ERROR:gpu_init.cc(426)] Passthrough is not supported, GL is egl
[44:44:0502/235901.330691:ERROR:sandbox_linux.cc(382)] InitializeSandbox() called with multiple threads in process gpu-process.
```
In all cases the VPXVideodecoder is used. I would really like to have video acceleration working.
I have the following flags enabled:

- ignore-gpu-blocklist
- enable-accelerated-video-decode

OS is Ubuntu 21.04. Would be really nice if we could get this to work in Wayland, either through XWayland or natively with Ozone.
Please let me know if it works for you!

**Comment by tinywrkb** [comment]
AFAIK it's broken with Ozone X11 or Wayland. Upstream Ozone X11 bug report is [here](https://bugs.chromium.org/p/chromium/issues/detail?id=1121948), but last time I check, the Ozone Wayland issue is not reported.

I don't know what `--use-gl=egl` is doing but if you want VAAPI working then you need to use the default, should've been sent to the grave a decade ago, GLX backend, and you can force it with `--use-gl=desktop-gl`.

**Comment by Esokrates** [comment]
Thanks for the pointers. Regarding `--use-gl=egl`: I have read in mutliple sources, that this makes vaapi work with XWayland, see for example here at https://wiki.archlinux.org/title/chromium#Hardware_video_acceleration where it says:
> To use system drivers on XWayland, use the `--use-gl=egl` flag. 

So @tinywrkb  do I understand you right, there is currently no way to make vaapi work in a Wayland session?

**Comment by tinywrkb** [comment]
> Regarding --use-gl=egl: I have read in mutliple sources, that this makes vaapi work with XWayland

This flag should do nothing, you are already using EGL if you have GPU acceleration enabled (rasterization, canvas, and etc) because Vulkan should be disabled as it's unstable and not very usable.  
The only thing this flag does for me is breaking the rendering of the UI. I tried with this Chromium build, stable Chrome, unstable/dev Chrome, and it's the same result.

> So @tinywrkb do I understand you right, there is currently no way to make vaapi work in a Wayland session?

This is a question for the devs and upstream. I didn't have any luck getting this to work.

**Comment by refi64** [comment]
I have never made VA-API succesfully run on Wayland using the native builds, so I don't believe this is really something we can fix.

> This flag should do nothing, you are already using EGL if you have GPU acceleration enabled

Note that there are other `use-gl=` options (`=desktop` was used for a while, and I believe the current default is `=angle` as of a...very recent M8X release). However, ANGLE *should* work with VA-API nowadays I believe.
