### ISSUE TITLE
Pass PipeWire capturer flag by default

### ISSUE THREAD

**Issue by vchernin** [flathub/org.chromium.Chromium#121]
PipeWire 0.3 currently [is built by default](https://github.com/flathub/org.chromium.Chromium/pull/88). However, for screen sharing to work on Wayland users need to run with `--enable-features=WebRTCPipeWireCapturer` or enable it in [chrome://flags](chrome://flags/#enable-webrtc-pipewire-capturer). I suggest passing the flag by default [in the .desktop file](https://github.com/flathub/com.slack.Slack/pull/118/commits/8552181dc907f00b9682c784c8876205098d3617), or [by building with it](https://github.com/jitsi/jitsi-meet-electron/pull/584/commits/0e0483cbc52a9cad1fef51ed5abb846bd6445b11) (if that’s feasible to do).

[Jitsi Meet Electron](https://github.com/jitsi/jitsi-meet-electron/pull/584) and [Slack Flatpak](https://github.com/flathub/com.slack.Slack/pull/118/) both pass this flag by default. [Slack support even suggests Wayland users pass the flag with Slack](https://github.com/flathub/com.slack.Slack/issues/101#issuecomment-808430530).

Of course this flag is there since Chromium’s PipeWire implementation is not yet perfect. There are bugs [like the dual pop up “dialog hell”](https://jgrulich.cz/2020/12/18/webrtc-chromium-updates-in-2020/) that can occur. However, I personally think mostly working screen sharing on Wayland by default is better than no screen sharing at all. Especially since it’s not obvious  users need to enable a flag to get working screen sharing. There is also a benefit of getting wider testing of this feature and hopefully useful PipeWire/Chromium bug reports. Also, running with the flag doesn’t seem to regress for X11 users.

If this isn’t a sensible idea perhaps a mention of the flag could be added to the Flathub page description. Also tab sharing works fine without the flag as that doesn’t use PipeWire.

Note there are currently WebRTC bugs [with PipeWire screen sharing on AMD](https://github.com/flathub/org.chromium.Chromium/pull/88#issuecomment-823788246), while Intel should work properly (it does for me). I don’t believe adding this flag would regress on AMD (as it doesn’t seem to work currently anyway), but it’s probably worth testing.

**Comment by wjt** [comment]
Sounds like a good idea in principle if it does not regress X11 usage. Perhaps it could be set in `chromium.sh`, the entry point in this package which invokes the browser. Fancy writing a PR?

**Comment by vchernin** [comment]
I tried it in `chromium.sh` in #131 but it didn't seem to have any effect. Would it be better to just pass it in the .desktop file instead? (that won't work with `flatpak run`).

**Comment by vchernin** [comment]
[See this comment](https://github.com/flathub/org.chromium.Chromium/pull/131#issuecomment-884612212). Doing this through a .conf file isn't currently really possible due to the current flag management system. When a better solution is available I can open a new PR.

**Comment by refi64** [comment]
So this will be doable shortly...but there is one more aspect to consider: right now, using Pipewire screen casting actually *segfaults* on AMD, so it doesn't just "not work" necessarily...that being said I'm not sure if it's *that* much worse I guess? Maybe we could detect `dma-buf-screen-sharing` being set somehow?

I know there's also work on the Mutter end to avoid sending DMA-BUFs to clients that can't handle it, but I, err, am not sure how that's going (I recall there being discussion on this during the XDG portals BoF, but 90% of it was going over my head so I kind of zoned out)...

@grulja sorry for the direct ping, but do you know if there are any particular updates on the end of this not crashing Chromium on AMD (regardless of where said updates are)? Would this be something worth enabling by default as-is?

**Comment by wjt** [comment]
@GeorgesStavracas as the orchestrator of said GUADEC BOF: thoughts?

**Comment by grulja** [comment]
> So this will be doable shortly...but there is one more aspect to consider: right now, using Pipewire screen casting actually _segfaults_ on AMD, so it doesn't just "not work" necessarily...that being said I'm not sure if it's _that_ much worse I guess? Maybe we could detect `dma-buf-screen-sharing` being set somehow?
> 
> I know there's also work on the Mutter end to avoid sending DMA-BUFs to clients that can't handle it, but I, err, am not sure how that's going (I recall there being discussion on this during the XDG portals BoF, but 90% of it was going over my head so I kind of zoned out)...
> 
> @grulja sorry for the direct ping, but do you know if there are any particular updates on the end of this not crashing Chromium on AMD (regardless of where said updates are)? Would this be something worth enabling by default as-is?

I plan to implement proper DMA-BUF support in Chromium soon, until then I can send you a patch which will disable it and avoid this issue.

**Comment by grulja** [comment]
This should do it for now until WebRTC properly supports DMA-BUFs:

```
diff --git a/modules/desktop_capture/linux/base_capturer_pipewire.cc b/modules/desktop_capture/linux/base_capturer_pipewire.cc
index e5d001e476..53a5c0b29d 100644
--- a/modules/desktop_capture/linux/base_capturer_pipewire.cc
+++ b/modules/desktop_capture/linux/base_capturer_pipewire.cc
@@ -324,7 +324,8 @@ void BaseCapturerPipeWire::OnStreamFormatChanged(void* data,
       &builder, SPA_TYPE_OBJECT_ParamBuffers, SPA_PARAM_Buffers,
       SPA_PARAM_BUFFERS_size, SPA_POD_Int(size), SPA_PARAM_BUFFERS_stride,
       SPA_POD_Int(stride), SPA_PARAM_BUFFERS_buffers,
-      SPA_POD_CHOICE_RANGE_Int(8, 1, 32)));
+      SPA_POD_CHOICE_RANGE_Int(8, 1, 32), SPA_PARAM_BUFFERS_dataType,
+      SPA_POD_Int((1 << SPA_DATA_MemPtr) | (1 << SPA_DATA_MemFd))));
   params[1] = reinterpret_cast<spa_pod*>(spa_pod_builder_add_object(
       &builder, SPA_TYPE_OBJECT_ParamMeta, SPA_PARAM_Meta, SPA_PARAM_META_type,
       SPA_POD_Id(SPA_META_Header), SPA_PARAM_META_size,

```

**Comment by grulja** [comment]
Ok, I already have a patch with proper DMA-BUFs support, seems to work for me on Intel graphics card. Is anyone here willing to give it a try? Maybe I can open a PR here with this patch so you can try it with a testing build.

**Comment by grulja** [comment]
Here it is, hopefully it builds: https://github.com/flathub/org.chromium.Chromium/pull/135

**Comment by refi64** [comment]
Already fixed.
