### ISSUE TITLE
Segmentation fault when opening YouTube

### ISSUE THREAD

**Issue by Schlipak** [flathub/org.chromium.Chromium#132]
Hi, I'm getting a segfault when I open a new YouTube tab on `Version 92.0.4515.107 (Official Build) (64-bit)`.
The issue doesn't seem constant, sometimes I may manage to open a tab without issues, but if I middle-click a video to open it in a new tab it pretty much always crashes. I'm unsure why this issue seem to be happening only for YouTube, I haven't had this issue for any other website for now.

I've ran Chromium through GDB using the .Debug extension, here's what comes up :

```
Thread 1 "chrome" received signal SIGSEGV, Segmentation fault.
base::OnceCallback<void (network::ResourceRequest const&, mojo::PendingReceiver<network::mojom::URLLoader>, mojo::PendingRemote<network::mojom::URLLoaderClient>)>::Run(network::ResourceRequest const&, mojo::PendingReceiver<network::mojom::URLLoader>, mojo::PendingRemote<network::mojom::URLLoaderClient>) && (this=0xbf607cb4648, args=..., args=..., args=...)
    at ../../base/callback.h:97
97	../../base/callback.h: No such file or directory.
```

The issue started happening right after I installed the latest version, I had no such issue on the previous version. It keeps happening even after reinstalling the app.

**Comment by refi64** [comment]
Could you run `bt` and grab a full back trace? We don't touch any code around there, so it might just be an upstream bug...

**Comment by Schlipak** [comment]
I tried running `bt` but gdb hangs, I let it run for an hour and still no output.
I had already tried rebooting twice yesterday to no avail, but somehow today I can't seem to reproduce the issue, I haven't updated anything system-wise but so far no crashes.

I think for now it's safe to attribute this to "a fluke" and close this issue.
