### ISSUE TITLE
Presence of Federated Learning of Cohorts component in Chromium

### ISSUE THREAD

**Issue by patriot4096** [flathub/org.chromium.Chromium#133]
chrome://components shows Federated Learning of Cohorts - Version: 1.0.6 in Version 92.0.4515.107 (Official Build) (64-bit).
Does it mean Google's FLOC is tracking Chromium Users?

**Comment by refi64** [comment]
Yes, FLoC is used in Chromium as well; you can disable it from `chrome://settings/privacySandbox`.
