### ISSUE TITLE
Very slow drag and drop

### ISSUE THREAD

**Issue by Chemrat** [flathub/org.chromium.Chromium#138]
Selecting some element and dragging it causes incredible lag. As I move my mouse, "dragged" element pixmap follows the cursor movement with at a very slow pace (takes seconds to retrace the mouse movement). This makes drag and drop borderline unusable. This does not seem to cause any visible CPU spike or something.

I'm on KDE, using nvidia proprietary driver 470.63.01.
Permissions:
```
$ flatpak info --show-permissions org.chromium.Chromium
[Context]
shared=network;ipc;
sockets=x11;wayland;pulseaudio;cups;
devices=dri;all;
filesystems=home;xdg-run/pipewire-0;/run/.heim_org.h5l.kcm-socket;

[Session Bus Policy]
org.gnome.SessionManager=talk
org.freedesktop.Notifications=talk
org.mpris.MediaPlayer2.chromium.*=own
org.freedesktop.secrets=talk
org.freedesktop.FileManager1=talk

[System Bus Policy]
org.freedesktop.Avahi=talk
org.freedesktop.UPower=talk

[Environment]
LD_LIBRARY_PATH=/app/chromium/nonfree-codecs/lib
GTK_PATH=/app/lib/gtkmodules
```

This happens with these flatpaks: `org.chromium.Chromium`, `com.google.Chrome` and `com.brave.Browser` (also based on chromium).
This **does not happen** with Firefox flatpak, Spotify flatpak, Discord flatpak. Discord is an electron application AFAIK so it's also based on chromium.
This **does not happen** with Chromium tarball from https://download-chromium.appspot.com/ running without flatpak.

Not really sure what kind of extra info I can provide to help pinpoint the issue.

**Comment by refi64** [comment]
Is this still reproducible? I'm...honestly not sure what might be causing it though.

**Comment by Chemrat** [comment]
Seems to be fixed for me now. Not sure when that happened.
