### ISSUE TITLE
Weird Dark Mode behaviour after update to 93

### ISSUE THREAD

**Issue by ariasmn** [flathub/org.chromium.Chromium#146]
As the title says.

I launch Chromium with the needed flags to force dark mode: `--force-dark-mode --enable=features=WebUIDarkMode`
However, after upgrading to v93, Chromium itself is in Dark Mode, but the right-click dialog window shows in light theme. See screenshot:
![issue](https://user-images.githubusercontent.com/33121576/132252300-8fc8cff3-fc1a-42fa-aa45-18dd052dde37.png)

Maybe this is a problem on my system (sorry in that case then), but I don't really know how to debug it. Please let me know how can I do so.
I'm using Debian 11 with KDE.

**Comment by refi64** [comment]
Is this still reproducible? Pretty sure it was an upstream issue.

**Comment by ariasmn** [comment]
> Is this still reproducible? Pretty sure it was an upstream issue.

Yes, you are right, seems like it was an upstream issue.

Closing, thank you so much!
