### ISSUE TITLE
Drop --filesystem=xdg-run/pipewire-0 from manifest

### ISSUE THREAD

**Issue by rmader** [flathub/org.chromium.Chromium#148]
The fact that screen sharing required Pipewire socked access despite using the xdg portal was a [WebRTC bug](https://webrtc-review.googlesource.com/c/src/+/230803). Once the fix has reached stable, `--filesystem=xdg-run/pipewire-0` can be dropped.

**Comment by vchernin** [comment]
On 96 with Intel I can remove `--filesystem=xdg-run/pipewire-0` with Flatseal and sharing still works.

As a sidenote, the DMA-BUF support [should be working now](https://jgrulich.cz/2021/10/06/dma-buf-support-in-webrtc/) for AMD, so is it time to look at https://github.com/flathub/org.chromium.Chromium/issues/121 again?

**Comment by refi64** [comment]
Already fixed.
