### ISSUE TITLE
Some H.264 videos stutter, even with .Codecs

### ISSUE THREAD

**Issue by wjt** [flathub/org.chromium.Chromium#15]
I wrote a much longer comment but then the browser ate it.

https://www.youtube.com/watch?v=c27RSDKx4vQ which is only available as H.264 stutters when played back with Chromium @ 69a609cb. It plays fine in Firefox from  Flathub (with `ffmpeg-full` installed) and system Chromium on Endless OS.

https://photos.app.goo.gl/NiHmnoawC6r37Xzs6 is a screen recording from my phone, in slow mo.

I think it may be an OpenH.264 limitation, but I have `org.chromium.Chromium.Codecs` installed so I would have expected that to be used in preference.

**Comment by wjt** [comment]
Yep, this video plays smoothly with the changes from #19

**Comment by fishxz** [comment]
weird, because twitch still stutters for me with this changes

**Comment by andrunko** [comment]
Yeah, weird indeed - https://www.youtube.com/watch?v=c27RSDKx4vQ still stutters for me also with latest from #19.

**Comment by andrunko** [comment]
The stutter happens with and without .Codecs installed - running org.flathub.Stable.Build31584.

**Comment by andrunko** [comment]
Ok, did some quick investigations and managed to get it working without stutter but only if I manually remove `/app/chromium/libffmpeg.so` (the free version) which in turn makes chromium uses `/app/chromium/nonfree-codecs/lib/libffmpeg.so` (from `org.chromium.Chromium.Codecs`). If I keep the free version around it will use it even though `.Codecs` adds the `nonfree-codecs/lib` dir to the lib path.

I also tried keeping the free version and setting `LD_LIBRARY_PATH` manually using the flatpak dev console but hit the same issue. I suspect this has something to do with https://github.com/flathub/org.chromium.Chromium/blob/l/patches/0005-Ensure-libffmpeg.so-is-in-the-rpath-of-binaries.patch which seems to always make chromium prefer the version in the same dir as the binary (the free version)?

**Comment by refi64** [comment]
I think if we switch from rpath to runpath it might fix it.

**Comment by andrunko** [comment]
This is fixed for me with the changes from https://github.com/flathub/org.chromium.Chromium/pull/24 (tested with build 31643).

**Comment by refi64** [comment]
Welp, it doesn't seem to be fixed over here:

```
[📦 org.chromium.Chromium configs]$ readelf -d /app/chromium/chrome | grep RPATH
 0x000000000000000f (RPATH)              Library rpath: [$ORIGIN]
[📦 org.chromium.Chromium configs]$ chromium --enable-logging=stderr --v=1 2>&1 | grep 264
[679:695:1119/195827.468264:VERBOSE1:flatpak_sandbox.cc(562)] Spawn() returned PID 110468
[679:679:1119/195832.141244:VERBOSE1:mime_util_internal.cc(327)] Using Cisco OpenH264
[732:735:1119/195832.172645:VERBOSE1:network_delegate.cc(32)] NetworkDelegate::NotifyBeforeURLRequest: https://accounts.google.com/ListAccounts?gpsia=1&source=ChromiumBrowser&json=standard
[774:21:1119/195832.469878:VERBOSE1:mime_util_internal.cc(327)] Using Cisco OpenH264
[760:10:1119/195832.504928:VERBOSE1:mime_util_internal.cc(327)] Using Cisco OpenH264
[759:9:1119/195832.606377:VERBOSE1:mime_util_internal.cc(327)] Using Cisco OpenH264
```

If I'm being honest I'm not sure why using is_component_ffmpeg worked for anyone *without* setting rpath, as another potential workaround I could play with adding `$ORIGIN/nonfree-codecs` in the rpath...

**Comment by andrunko** [comment]
Oh indeed, my bad, I just retested and it still fails indeed - I think I had moved the free one out of the way by mistake while testing...

**Comment by andrunko** [comment]
Fwiw, the system chromium shipped by Endless has no `RPATH` set (and we set `LD_LIBRARY_PATH` in the chromium startup script with the nonfree-codecs as first entry and always including the binary location as well).

```
andrunko@endless-master-vm:~$ file /usr/lib/chromium-browser/chromium-browser 
/usr/lib/chromium-browser/chromium-browser: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=d79b545018f4536ae38d43d56b2c64445a3ac55a, stripped
andrunko@endless-master-vm:~$ readelf -d /usr/lib/chromium-browser/chromium-browser | grep RPATH
```

Our startup script has:
```
LIBDIR=/usr/lib/chromium-browser
EXTRA_CODECS_DIR=/var/lib/codecs/chromium-browser
...

# FFmpeg needs to know where its libs are located
if [ "Z$LD_LIBRARY_PATH" != Z ] ; then
  LD_LIBRARY_PATH=$EXTRA_CODECS_DIR:$LIBDIR:$LD_LIBRARY_PATH
else
  LD_LIBRARY_PATH=$EXTRA_CODECS_DIR:$LIBDIR
fi

...
```

**Comment by andrunko** [comment]
Ok, I see what is happening:

We include [this patch](https://github.com/endlessm/chromium-browser/commit/908c479f31586db62c59e72457a05c9df14bcefe) a patch to set RPATH.

But then in our packaging we have:
```
        # Convert rpath to runpath if needed, so that LD_LIBRARY_PATH (set in our launcher script)
        # takes precedence. This is required for Endless extra codecs to work properly.
        chrpath --convert debian/tmp/$(LIB_DIR)/chrome || true
```

Confirmed with:
```
andrunko@endless-master-vm:~$ readelf -d /usr/lib/chromium-browser/chromium-browser | grep RUNPATH
 0x000000000000001d (RUNPATH)            Library runpath: [$ORIGIN]
```
