### ISSUE TITLE
Chromium is not able to communicate the theme of its host system to webpages.

### ISSUE THREAD

**Issue by BEEDELLROKEJULIANLOCKHART** [flathub/org.chromium.Chromium#168]
Although I have configured the theme of my desktop environment to be to be 'http://github.com/flathub/org.gtk.Gtk3theme.Adwaita-dark', which is obviously dark, 'http://github.com/flathub/org.chromium.Chromium' is not able to communicate my preference to any website. Conection to 'http://youtube.com' is demonstrative of this regression. 'http://github.com/flathub/org.mozilla.firefox.BaseApp' is able to communicate this, so this problem is not because of 'http://github.com/flatpak/flatpak', and 'http://github.com/chromium/chromium' is able to perform this operation, so this regression is specific to this package.

**Comment by refi64** [comment]
Afaik this doesn't work at all on upstream chromium, there are open bugs about it. Are you sure it works with regular chromium, it's not a downstream patch that version has?

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
You are correct.
