### ISSUE TITLE
Full-screen videos don't prevent Screen Locking or Dimming/Sleeping

### ISSUE THREAD

**Issue by Victor239** [flathub/org.chromium.Chromium#171]
SUMMARY
Using Flatpak Chromium v95.0.4638.54 and have tested watching full-screen videos, found screen locking and dimming still occurs. 

STEPS TO REPRODUCE
1. Set screen locking or dimming to 1 min
2. Full-screen any YouTube video (also found the same with Jellyfin videos)

OBSERVED RESULT
It'll still screen lock/dim.

EXPECTED RESULT
Unlike full-screen videos in VLC, FreeTube, Firefox etc which all prevent screen locking/dimming whilst watching.

SOFTWARE/OS VERSIONS
Linux/KDE Plasma: Kubuntu 21.10
(available in About System)
KDE Plasma Version: 5.23.1
KDE Frameworks Version: 5.87.0
Qt Version: 5.15.2

**Comment by chrisx8** [comment]
Hi @Victor239,

I just submitted PR #204, which should fix this issue. It would be really helpful if you can help me test it.

How to test:
- Close all Chromium windows
- Launch Chromium with:
  ```
  flatpak run --talk-name=org.freedesktop.ScreenSaver org.chromium.Chromium
  ```
- Play media (such as a YouTube video) in Chromium, and see if computer turns off the screen, starts screensaver, or automatically suspends.
