### ISSUE TITLE
Question regarding GN arguments

### ISSUE THREAD

**Issue by TheHooly** [flathub/org.chromium.Chromium#175]
Does this build include the following gn build arguments?

```
is_offical_build=true
is_debug=false
is_component_build=false
```

Explanation:

`is_official_build`
Set to enable the official build level of optimization. This has nothing to do with branding, but enables an additional level of optimization above release (!is_debug). Defaults to `false`. 
Should be enabled for builds intended for users.
 
`is_debug`
Debug build. Defaults to `true`.
Should be disabled for builds intended for users.

`is_component_build`
Component build. Setting to true compiles targets declared as "components" as shared libraries loaded dynamically. This speeds up development time. When false, components will be linked statically. Defaults to `true`.
Should be disabled for builds intended for users. This extends clang's CFI to the statically-linked libraries, improving security.

Source: https://gitlab.com/noencoding/OS-X-Chromium-with-proprietary-codecs/-/wikis/List-of-all-gn-arguments-for-Chromium-build

If not, please include them in future builds, thank you.

**Comment by Erick555** [comment]
Thanks to all build scripts being available in this repo it takes just few seconds to [find out](https://github.com/flathub/org.chromium.Chromium/blob/master/build-aux/bootstrap.sh#L23). :smile:

**Comment by refi64** [comment]
All of these are indeed set, but really we only set `is_official_build = true` explicitly:

- `is_debug` is [automatically disabled when `is_official_build` is set](https://source.chromium.org/chromium/chromium/src/+/main:third_party/devtools-frontend/src/build_overrides/BUILDCONFIG.gn;l=48;drc=1f19e63ccb191cc1a8294685c2a6d3af90180420)
- `is_component_build` is [only set when `is_debug` is set](https://source.chromium.org/chromium/chromium/src/+/main:build/config/BUILDCONFIG.gn;l=168;drc=1857aa7cfed5da7a68440de8b634e5ca5309c9d6)

So they don't all need to be explicitly set.
