### ISSUE TITLE
Dns lookup is very slow

### ISSUE THREAD

**Issue by sebastiencs** [flathub/org.chromium.Chromium#18]
When I type an address in the search bar, it takes ~8 seconds to resolve the domain:

![Screenshot from 2020-11-18 06-22-23](https://user-images.githubusercontent.com/5273820/99458223-19012900-2924-11eb-8cad-c2d7c241ea6c.png)

This occurs with all domains.

Not sure if it's an issue with flatpak itself or chromium.
Let me know what informations I can provide to help resolve this.

**Comment by refi64** [comment]
Huh, this is weird...

- What's the contents of your `/etc/resolv.conf`?
- What distro is your host system?
- Do you use any local custom DNS resolvers like unbound or systemd-resolved?
- Can you try a standard Chrome or Chromium build to see if this is reproducible outside the Flatpak?

**Comment by sebastiencs** [comment]
It was a problem with my configuration, sorry for the noise
