### ISSUE TITLE
Starting with wayland backend fails

### ISSUE THREAD

**Issue by binaryfields** [flathub/org.chromium.Chromium#195]
Recently, starting Chromium with wayland support stopped working.  To repro, run the following commands  under wayland desktoip session:

> flatpak override org.chromium.Chromium --socket=wayland
> flatpak run org.chromium.Chromium -enable-features=UseOzonePlatform -ozone-platform=wayland

I get the following log message:

>  interface 'wl_output' has no event 4
>  [0126/153616.134852:ERROR:scoped_ptrace_attach.cc(27)] ptrace: Operation not permitted (1)

My environment:
Distro: Arch
Desktop: Sway 1.7

It would be good to know if you can also repro this issue and if its something new introduced in v97.

Thanks
-Sebastian

**Comment by tinywrkb** [comment]
Maybe https://bugs.chromium.org/p/chromium/issues/detail?id=1279574

**Comment by binaryfields** [comment]
That will do it. Thanks!

**Comment by tinywrkb** [comment]
@binaryfields maybe keep this issue open, until it's actually fixed here, as the issue could be ported back and applied to this app.
