### ISSUE TITLE
Add patch to enable hardware acceleration under wayland

### ISSUE THREAD

**Issue by chaibronz** [flathub/org.chromium.Chromium#197]
Chromium can be patched to support vaapi hardware acceleration under wayland. I've seen a patch for this in the AUR and used it to patch a version of Chromium in the [OpenSUSE build service](https://build.opensuse.org/package/show/home:h3o/chromium-wayland). Would there be any appetite to include this patch in the Flatpak version? I don't believe it would create any issues, and it would only be enabled if the user explicitly launched the application with the appropriate flags (not sure if all these are necessary but they do the trick for me): 

--enable-features=UseOzonePlatform \
--ozone-platform=wayland \
--ignore-gpu-blocklist \
--enable-gpu-rasterization \
--enable-zero-copy \
--disable-gpu-driver-bug-workarounds \
--enable-accelerated-video-decode \
--enable-features=VaapiVideoDecoder \
--use-gl=egl

[chromium-97-wayland-vaapi.patch.txt](https://github.com/flathub/org.chromium.Chromium/files/7975319/chromium-97-wayland-vaapi.patch.txt)

**Comment by chaibronz** [comment]
nevermind, i see this was already discussed #187

**Comment by refi64** [comment]
Indeed, VA-API is also undergoing some major re-implementation work upstream, so pulling the patch in isn't viable atm.

**Comment by 4oo4** [comment]
fwiw, vaapi seems to work well in the ungoogled Chromium flatpak for now (https://github.com/flathub/com.github.Eloston.UngoogledChromium), I wonder what vaapi patches they are using.

**Comment by refi64** [comment]
The UCG Flatpak does not have any different patches related to this...so I'm interested that it's working for you there.

Native Wayland support for VA-API is tracked [here](https://bugs.chromium.org/p/chromium/issues/detail?id=1237371) but I'm not sure of the status. I know the LaCrOS effort probably depends on this, but the only bug related to that [was moved to the private tracker](https://bugs.chromium.org/p/chromium/issues/detail?id=1204231). That being said, there is [active effort in that direction](https://chromium-review.googlesource.com/q/owner:pmolinalopez%2540google.com), so maybe this started working at some point?

Are you using any different graphics-related flags with standard Chromium vs UCG?

**Comment by 4oo4** [comment]
So interestingly, when I was going to compare flags and command line args I noticed that now this repo is working for VAAPI now. I think there was an update to the `org.freedesktop.Platform.VAAPI.Intel` that I remember seeing, commit is `45d65f23e5f7`. It might also have been an update of this app? I'm trying to track down my flatpak history to confirm.
