### ISSUE TITLE
Need to test extension points

### ISSUE THREAD

**Issue by refi64** [flathub/org.chromium.Chromium#2]
- Widevine.
- Native messaging hosts.
- Policies.

**Comment by refi64** [comment]
Widevine **does not work**: the paths were set incorrectly in chrome_paths.cc.

**Comment by refi64** [comment]
Widevine and policies are now confirmed to work.

**Comment by GiantEnemyCrab** [comment]
Was "Native messaging hosts" metioned for errors like 
`Although GNOME Shell integration extension is running, native host connector is not detected. Refer documentation for instructions about installing connector.` when visiting https://extensions.gnome.org/?

I do have done
```
sudo apt-get install chrome-gnome-shell
```
, but flatpak chromuim installation seems not aware of that.

**Comment by refi64** [comment]
Since Chromium is Flatpak'd, it needs a separate extension with its own native host inside.
