### ISSUE TITLE
WebGl not working with hardware acceleration disabled

### ISSUE THREAD

**Issue by liborat** [flathub/org.chromium.Chromium#200]
WebGL does not work with hardware acceleration disabled.  Even if I enable hardware acceleration WebGL does not work since I believe my gpu is blacklisted.  chrome://gpu says that WebGL is disabled.  I seem to be missing the files libvulkan.so.1 and vk_swiftshader_icd.json from /var/lib/flatpak/app/org.chromium.Chromium/x86_64/stable/<abcd...>/files/chromium.  When I add them from the extracted contents of the google-chrome-stable_current_amd64.deb download WebGL works again and chrome://gpu says that WebGL has software only, hardware acceleration is disabled.  This seems to be similar to the snap chromium bug the 5th and 6th posts.

https://bugs.launchpad.net/ubuntu/+source/chromium-browser/+bug/1959416

**Comment by hyuri** [comment]
Same here.
Pop!_OS 21.10
HD Graphics 4000 (Intel i7)
Nvidia Geforce GT 630M

My Nvidia card doesn't seem to be running, so the issue seems to be with the HD Graphics 4000.

**Comment by refi64** [comment]
Will likely be fixed by #201.

**Comment by hyuri** [comment]
Solved after update for me.
