### ISSUE TITLE
No screensharing in Google Meet

### ISSUE THREAD

**Issue by wjt** [flathub/org.chromium.Chromium#21]
Regardless of which option I pick from this menu:

![Capture d’écran de 2020-11-18 18-07-30](https://user-images.githubusercontent.com/86760/99569771-f37a2b00-29c8-11eb-8bea-fe73b35bf601.png)

I see:

![Capture d’écran de 2020-11-18 17-33-36](https://user-images.githubusercontent.com/86760/99569811-03920a80-29c9-11eb-82ca-9063a1bd7cea.png)

On Endless OS master with X11

**Comment by cungureanu** [comment]
**enable_hangout_services_extension=true** GN has to be set

**Comment by wjt** [comment]
> **enable_hangout_services_extension=true** GN has to be set

Ah yes, it's only Google Meet. Jitsi Meet can do screensharing just fine.
