### ISSUE TITLE
Built without Pipewire support

### ISSUE THREAD

**Issue by wjt** [flathub/org.chromium.Chromium#22]
Split from #21 because these things are not actually related.

Official Chrome binaries have a flag in chrome://flags/ to make Chrome use Pipewire to do screensharing on Wayland systems. This Flatpak of Chromium does not have that option. Based on https://github.com/NixOS/nixpkgs/issues/89528, this needs `rtc_use_pipewire=true` build flag, and for libpipewire to be present. I do not know whether the libpipewire-0.3 in the SDK is usable by Chromium.

**Comment by tpopela** [comment]
I note here. We will be able to drop the requirement on PipeWire 0.2 in Chromium 89. Or if you are not opposed for taking a temporary patch, you can backport the PipeWire 0.3 support with:

https://webrtc.googlesource.com/src/+/40c3ea5c7146cb7ec2fa999143d702b8825b725f
https://webrtc.googlesource.com/src/+/c3c81297365b6a293480f7af7ce5df632324b9e1

and ideally with https://chromium-review.googlesource.com/c/chromium/src/+/2578840 that should be merged soon (this will avoid the multiple dialogs (for previews and screen sharing itself).

One thing that could also be done would be to enable the PipeWire by default (by changing https://source.chromium.org/chromium/chromium/src/+/master:content/public/common/content_features.cc;l=975?q=kWebRtcPipeWireCapturer&ss=chromium)

**Comment by grulja** [comment]
Also, in case you backport support for PipeWire 0.3, you will have to specify `rtc_pipewire_version = "0.3"` as we default to "0.2".

**Comment by refi64** [comment]
Ah nice, unless it's a major user experience hit it would probably be better just to wait for upstream though.
