### ISSUE TITLE
Missing from GNOME Software

### ISSUE THREAD

**Issue by ahayzen** [flathub/org.chromium.Chromium#220]
When I search for Chromium in GNOME Software with flathub enabled it cannot find Chromium (but it can find Chrome). Is something wrong with the appdata ?

**Comment by wjt** [comment]
Very weird – I can reproduce on GNOME OS nightly. If I search for `org.chromium` it is found; or "project", or "browser"; but not "chromium".

**Comment by wjt** [comment]
```
wjt@camille:~$ appstreamcli validate --pedantic /var/lib/flatpak/app/org.chromium.Chromium/current/active/files/share/app-info/xmls/org.chromium.Chromium.xml.gz 
W: org.chromium.Chromium:22: mimetypes-tag-deprecated
P: org.chromium.Chromium:4: cid-contains-uppercase-letter org.chromium.Chromium
P: org.chromium.Chromium:41: screenshot-no-caption
W: org.chromium.Chromium:~: releases-not-in-order 85.0.4183.121 << 88.0.4324.96
I: org.chromium.Chromium:19: nonstandard-gnome-extension kudos
```

Not especially helpful!

**Comment by rany2** [comment]
This should be fixed with https://github.com/flathub/com.github.Eloston.UngoogledChromium/commit/a0796102e49fed9a2a2af5110d8445f7e0d6555d
