### ISSUE TITLE
Chromium doesn't detect system theme on Linux (Gnome/Flatpak)

### ISSUE THREAD

**Issue by jaysonwcs** [flathub/org.chromium.Chromium#245]
# Bug Report

## Bug Description
Chromium does not detect the correct system theme.

## Steps To Reproduce
- Install Chromium via Flatpak (Flathub repository)
- Switch Gnome to dark mode
- Open developer mode (ctrl + shift + i)
- Execute this code on the console: `matchMedia('(prefers-color-scheme: dark)').matches`

## Expected Behavior
After switching Gnome to dark mode, it's expected to Chromium report the result from the previous command as `true`.

## Actual Behavior
Chromium reported the result from the previous command as `false`.

## Screenshots
![image](https://user-images.githubusercontent.com/7007373/191267837-189451ad-68a5-45fc-8179-e912bb3b70e2.png)

## System Information
- OS: Linux (Arch Linux, Kernel: Linux Desktop 5.19.7-arch1-1 # 1 SMP PREEMPT_DYNAMIC Mon, 05 Sep 2022 18:09:09 +0000 x86_64 GNU/Linux)
- Chromium 105.0.5195.125

## Additional Context
This feature is important to allow some extensions and websites that depends on detecting the system theme.
The browser main theme switches accordingly. The problem occurs only internally (through JavaScript code).

**Comment by refi64** [comment]
This is a known upstream issue.

**Comment by jaysonwcs** [comment]
@refi64 , could you show me the link to the original issue?
Thanks.

**Comment by jaysonwcs** [comment]
Never mind, I found it: https://bugs.chromium.org/p/chromium/issues/detail?id=998903&q=matchMedia%28%27%28prefers-color-scheme%3A%20dark%29%27%29.matches&can=2
