### ISSUE TITLE
Metainfo showing outdated version; Chromium having access to $HOME

### ISSUE THREAD

**Issue by TheEvilSkeleton** [flathub/org.chromium.Chromium#25]
The metainfo is showing an outdated version of Chromium: https://github.com/flathub/org.chromium.Chromium/blob/beta/org.chromium.Chromium.metainfo.xml#L29.

As seen in GNOME Software:
![image](https://user-images.githubusercontent.com/50847364/99805770-fd0bac00-2b0a-11eb-9284-f4d1950e60f7.png)

---

Another thing is that the flatpak now has access to $HOME: https://github.com/flathub/org.chromium.Chromium/blob/beta/org.chromium.Chromium.yaml#L8. Not sure if it was intended or not, I just wanted to point that out.

**Comment by refi64** [comment]
Yeah I'll update the metainfo version soon :sweat_smile: 

> Another thing is that the flatpak now has access to $HOME

[Intentional](https://github.com/flathub/org.chromium.Chromium/pull/19#issuecomment-730088310):

**Comment by refi64** [comment]
You can make nofilesystem=home work by enabling the file chooser portal in `chrome://flags`, but note that clicking a downloaded file to open it will *not* work due to the above bug.
