### ISSUE TITLE
Not opening in a native Wayland window

### ISSUE THREAD

**Issue by TheEvilSkeleton** [flathub/org.chromium.Chromium#26]
Wayland is enabled since https://github.com/flathub/org.chromium.Chromium/commit/818d57bc12c9cafec77bd2b32dd38e3f772f178b. I'm using stock permissions of the flatpak (only with X11 disabled), but it doesn't seem to be working:

```
    ~ 
flatpak override --user --show org.chromium.Chromium
[Context]
sockets=!x11
    ~ 
flatpak run org.chromium.Chromium
[2:2:1120/084729.791197:ERROR:browser_main_loop.cc(1434)] Unable to open X display.
```

**Comment by GeorgesStavracas** [comment]
You need to pass `--enable-features=UseOzonePlatform --ozone-platform=wayland`. This is a conscious decision made by upstream, because not everything is implemented on Wayland yet. I don't think this is an issue.

**Comment by TheEvilSkeleton** [comment]
I see, thank you. It worked.
