### ISSUE TITLE
Update to latest version

### ISSUE THREAD

**Issue by xcvfxq** [flathub/org.chromium.Chromium#267]
The version of Chromium available on Flathub is 108.0.5359.124, despite version 109 having been released over a week ago.

The most recent [build](https://buildbot.flathub.org/#/builders/6/builds/16642) on Flathub appears to have failed at the publishing step.

**Comment by wjt** [comment]
Triggered a rebuild https://buildbot.flathub.org/#/builders/6/builds/18360
