### ISSUE TITLE
color picker eyedropper fails to function

### ISSUE THREAD

**Issue by kinghat** [flathub/org.chromium.Chromium#269]
this seems to be a problem with all flatpak chrom* based browsers for me. when selecting the color picker(eyedropper) i either nothing happens or i get a quick flash of a portal dialogue and this it disappears. can test here: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input/color

on kde wayland fedora 37

**Comment by wjt** [comment]
Looks like Chromium is trying to use the screenshare portal to pick a colour; but it should use the screenshot portal's [PickColor()](https://flatpak.github.io/xdg-desktop-portal/#gdbus-method-org-freedesktop-portal-Screenshot.PickColor) method.

**Comment by kinghat** [comment]
> Looks like Chromium is trying to use the screenshare portal to pick a colour; but it should use the screenshot portal's [PickColor()](https://flatpak.github.io/xdg-desktop-portal/#gdbus-method-org-freedesktop-portal-Screenshot.PickColor) method.

so this wouldnt have anything to do with flatpak, and is the same for unpakd chromium?

**Comment by wjt** [comment]
I don't know for sure. My guess is yes, if the host system uses Wayland.

**Comment by kinghat** [comment]
thanks for the reply. closing as irrelevant then.
