### ISSUE TITLE
Wire up flatpak-external-data-checker

### ISSUE THREAD

**Issue by wjt** [flathub/org.chromium.Chromium#29]
Chromium releases very frequently: new major releases every 6 weeks, and there are often 1-3 patches in between major releases which fix major security issues.

https://github.com/flathub/flatpak-external-data-checker exists to automatically open PRs for new releases.

Whether by adding a Chromium-specific checker or by wiring up one of the existing scrapers, we should arrange for flatpak-external-data-checker to open PRs for this repo. (@andrunko please correct me if I'm wrong, but) the patches Endless OS's built-in chromium package carries would typically apply cleanly to point releases, but often needed some minor refreshments to apply to new major versions. I still think the failed PR build for a new major version is useful as a reminder to do that refreshment.

**Comment by andrunko** [comment]
> @andrunko please correct me if I'm wrong, but) the patches Endless OS's built-in chromium package carries would typically apply cleanly to point releases, but often needed some minor refreshments to apply to new major versions. I still think the failed PR build for a new major version is useful as a reminder to do that refreshment.

Yes, that is correct, I also agree having the PR would help even if it fails to build (if only to notify when there is a new upstream release available).

**Comment by refi64** [comment]
I'm not entirely sure how this would be wired up without adding some extra
stuff to the external data checker first. It often take a few hours for the
source tarballs to go up after pretty much all release announcements to go
up, so the main other way would be go query the Cloud Storage APIs for new
tarballs, *but* that doesn't seem to provide any way to distinguish stable
releases so that would have to be done some other way...

**Comment by gasinvein** [comment]
Can we use https://omahaproxy.appspot.com? I'm not sure if it's the official way to check for Chromium releases, but it seems to be what people are using.

**Comment by andrunko** [comment]
Yes, I think so, it also supports filtering the json: https://omahaproxy.appspot.com/all.json?os=linux;channel=stable.
