### ISSUE TITLE
Alias for chromium on linux 

### ISSUE THREAD

**Issue by jhenrii93** [flathub/org.chromium.Chromium#296]
Hi everyone !

I made this alias on my ubuntu to open chromium from terminal : alias chromium="flatpak run org.chromium.Chromium";
but when i want to open a html file its open in a new tab. What should i chage in the alias to open in a new window instead?

**Comment by wjt** [comment]
I searched for `chromium command line arguments` and found this page https://peter.sh/experiments/chromium-command-line-switches/ which suggests that the command-line argument is `--new-window`.
