### ISSUE TITLE
Can't start in Debian Buster

### ISSUE THREAD

**Issue by Doc73** [flathub/org.chromium.Chromium#31]
Dear Mantainers,
This is the error I receive every time I try to run chromium:

`Your Flatpak version does not support the expose-pids flag, 
which means that Chromium is unable to run. This generally
happens if your distro's bubblewrap installation is setuid
instead of using user namespaces.`

I'm running Debian Buster AMD64.
I installed chromium a few minutes ago.

Many thanks and best regards,
DC

**Comment by rany2** [comment]
Hello, 

This isn't `org.chromium.Chromium`'s fault. If you want it to work on Debian properly you'll have to run the following commands:

```sh
echo 'kernel.unprivileged_userns_clone=1' >> /etc/sysctl.conf
sysctl -p 
bash -c 'chmod -s $(which bwrap)'
bash -c 'dpkg-statoverride --add --update root root 0755 $(which bwrap)'
```

**Comment by Doc73** [comment]
Ah, thanks!
Does this change affect security?

**Comment by rany2** [comment]
I am not sure if it's that big of a deal but you should know Debian is the only major distro that has user namespaces disabled. All the other distros and the official linux kernel don't disable user namespaces by default and actually can't disable user namespaces. Even Ubuntu which is based on Debian has it enabled.   

There have been some vulnerabilities with enabling that feature (all the known ones are fixed now) but I don't think it should be that concerning for the majority of users. For the most part it's safe

**Comment by rany2** [comment]
grsecurity has a patch similar to the one that Debian uses but that is about it

**Comment by Doc73** [comment]
Thank you very very much for your kind explanations.
I will read up on the matter carefully.
Many thanks again and best regards

**Comment by Erick555** [comment]
See also discussion in https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=898446

**Comment by refi64** [comment]
The dialog should probably say more info, it's not super descriptive atm...

**Comment by Erick555** [comment]
It seems that next debian version will have [unpriv user ns by default](https://salsa.debian.org/kernel-team/linux/-/commit/a381917851e762684ebe28e04c5ae0d8be7f42c7).

**Comment by adrelanos** [comment]
Reported to Debian.
[org.chromium.Chromium broken in Debian buster](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=977758)

**Comment by Doc73** [comment]
Still not working!
I receive this message:
![chromium](https://user-images.githubusercontent.com/1306260/108181243-f7246780-7107-11eb-8f4d-83a1b1ffcd63.png)

But...
```
$ apt policy flatpak
flatpak:
  Installato: 1.10.1-1~bpo10+1
  Candidato:  1.10.1-1~bpo10+1
  Tabella versione:
 *** 1.10.1-1~bpo10+1 100
        100 http://deb.debian.org/debian buster-backports/main amd64 Packages
        100 /var/lib/dpkg/status
     1.2.5-0+deb10u3 500
        500 http://deb.debian.org/debian buster/main amd64 Packages
        500 http://security.debian.org/debian-security buster/updates/main amd64 Packages

$ apt policy bubblewrap
bubblewrap:
  Installato: 0.4.1-3~bpo10+1
  Candidato:  0.4.1-3~bpo10+1
  Tabella versione:
 *** 0.4.1-3~bpo10+1 100
        100 http://deb.debian.org/debian buster-backports/main amd64 Packages
        100 /var/lib/dpkg/status
     0.3.1-4 500
        500 http://deb.debian.org/debian buster/main amd64 Packages

$ uname -a
Linux desktop 5.10.0-0.bpo.3-amd64 #1 SMP Debian 5.10.13-1~bpo10+1 (2021-02-11) x86_64 GNU/Linux
```
:cry:

**Comment by refi64** [comment]
@Doc73 apologies for the delay, what's the output of

```
$ cat /proc/sys/kernel/unprivileged_userns_clone
$ ls -l /usr/bin/bwrap
```

also, do you see any errors when you `flatpak run org.chromium.Chromium` from the CLI?

**Comment by Doc73** [comment]
@refi64 
```
~$ cat /proc/sys/kernel/unprivileged_userns_clone
1
~$ ls -l /usr/bin/bwrap
-rwsr-xr-x 1 root root 63776 gen  8 10:24 /usr/bin/bwrap
```
No errors wen running Chromium from the CLI; only the window above posted

**Comment by Erick555** [comment]
You didn't removed setuid bit from bwrap, you may follow instructions from https://github.com/flathub/org.chromium.Chromium/blob/master/portal_error.txt#L17 to fix that.

**Comment by Doc73** [comment]
@Erick555 
Yes, not it works, but the instructions to fix this issue talk about "other distros": I'm using Debian Buster! :smile:

**Comment by refi64** [comment]
I'll add an updated message to #89 when it gets merged in.
