### ISSUE TITLE
Crash when opening a new regular window (Ctrl + N) or incognito window (Ctrl + Shift + N) in a incognito window

### ISSUE THREAD

**Issue by hyuri** [flathub/org.chromium.Chromium#311]
If I have an incognito window open, and I press Ctrl + N / Ctrl + Shift + N to open a regular / incognito window, the app crashes.

This is the message I get after the crash, when running the app via the terminal:
`[0908/003257.214738:ERROR:scoped_ptrace_attach.cc(27)] ptrace: Operation not permitted (1)`

**Comment by hyuri** [comment]
Updated description to include crash terminal output.

**Comment by violetmage** [comment]
What version of flatpak are you using?

**Comment by hyuri** [comment]
@violetmage Flatpak 1.14.4

**Comment by refi64** [comment]
`scoped_ptrace_attach` are unrelated; they happen *after* a crash occurs. Out of curiosity, have you checked if anything on https://bugs.chromium.org matches? This sounds like something that would be an upstream bug.

**Comment by hyuri** [comment]
I haven't, but I did test Brave and the same issue occurred, so it indeed seems to be an upstream bug.
