### ISSUE TITLE
The latest update broke twitch.tv (error: #4000) [SEE COMMENTS FOR WORKAROUND]

### ISSUE THREAD

**Issue by Lancer11211** [flathub/org.chromium.Chromium#340]
Starting with the latest update, no twitch video/stream can be played. A fresh flatpak installation doesn't help. I assume ffmpeg is missing.

**Comment by regulator-g** [comment]
yep seems a lot of web media is broken, if anyone is stuck you can revert to the last version until its fixed:

sudo flatpak update --commit=885e60ce680c5418885c4f540be7812714fa77a74c685803179312ecd2042006 org.chromium.Chromium

**Comment by AndrejSh3** [comment]
I've noticed problems playing media on the following websites as well:
- Instagram
- Netflix
- Spotify

The same issue doesn't occur with the Google Chrome flatpak

**Comment by ntippie** [comment]
`chrome://media-internals` gave the error `Cannot select FFmpegAudioDecoder for audio decoding`. Downgrade worked, thank you.

**Comment by refi64** [comment]
Working on a fix, but as a temporary workaround, you can pass `--disable-features=FFmpegAllowLists` or add `features-=FFmpegAllowLists` to your `chromium-flags.conf`.

**Comment by Erick555** [comment]
It's confusing that chromium flatpak uses libfdk-aac and openh264 also in non-free codecs extension specially when quality is below native ffmpeg decoders.

**Comment by refi64** [comment]
OpenH264 is for the free codecs only, where AAC is also disabled. libfdk-aac is used for the non-free codecs, specifically for *decoding*, where it's equivalent to FFmpeg's native AAC decoder.  (As an aside, for *encoding*, the superior one is [actually libfdk-aac, not FFmpeg's native encoder](https://superuser.com/a/1610768). I've seen some discussion about the native one being superior, but I never saw it backed by any evidence.)

**Comment by Erick555** [comment]
Note that freedesktop runtime ships stripped version of libfdk-aac where some features are [removed](https://gitlab.com/freedesktop-sdk/mirrors/freedesktop_people/fdk-aac/-/commits/stripped4/?ref_type=heads) in order to make it patent free.
