### ISSUE TITLE
Move to fsdk 23.08

### ISSUE THREAD

**Issue by Erick555** [flathub/org.chromium.Chromium#344]
Most popular apps on flathub moved to freedesktop-sdk 23.08 already so users will benefit if chromium migrated to it as well (installing additional runtime is 1GB+ of additional disk space).

https://github.com/flathub/org.chromium.Chromium.BaseApp/pull/30 is prerequsite for this.

**Comment by theofficialgman** [comment]
I second moving to 23.08, this would move to GLIBC 2.38 and allow for patched Widevine ARM64 to be used as seen here -> https://github.com/AsahiLinux/widevine-installer

**Comment by OlivierDoriath** [comment]
I would also like to see this happen!

**Comment by Erick555** [comment]
You can test 23.08 version [here](https://github.com/flathub/org.chromium.Chromium/pull/346#issuecomment-1894294541)
