### ISSUE TITLE
Refresh VAAPI patches

### ISSUE THREAD

**Issue by Alt37** [flathub/org.chromium.Chromium#35]
Upstream Chromium:
* added "chrome flag" for VAAPI decoding in version 86 (#enable-accelerated-video-decode) . Commit ['Allow the flag disable-accelerated-video-decode to be disabled on linux'](https://github.com/chromium/chromium/commit/a59445228676c7f517905f896ee71eaf3741d4bc#diff-b98ee78788d24ecc151c3f8e74fef65be502cb8f1e28fe591d5cfb54010c8a96)
* Set "use_vaapi" flag by default in version 88 (required for "chrome flag" to work). Commit ['Reland "Enable vaapi decoding on linux x86/64 by default." '](https://github.com/chromium/chromium/commit/d658439002fc9bc6b4deeec71738600402ea9742#diff-fa163b664861acb517b8a57ea9fda19f2763df562e38d4d82de346b0ddbea810)
That means that with version 88 we'll probably have VAAPI support out of box for most Chromium builds.

So my proposes for current version 87:
* Drop patch "0013-Enable-VAVDA-VAVEA-and-VAJDA-on-linux-with-VAAPI-onl.patch". It's large and obsolete now.
* Integrate [Fedora patches](https://src.fedoraproject.org/rpms/chromium/tree/master) to make VAAPI experience even better ( specifically [chromium-88-vaapi-attribute.patch](https://src.fedoraproject.org/rpms/chromium/raw/master/f/chromium-88-vaapi-attribute.patch) , [chromium-86.0.4240.75-fix-vaapi-on-intel.patch](https://src.fedoraproject.org/rpms/chromium/raw/master/f/chromium-86.0.4240.75-fix-vaapi-on-intel.patch) , [chromium-86.0.4240.75-enable-hardware-accelerated-mjpeg.patch](https://src.fedoraproject.org/rpms/chromium/raw/master/f/chromium-86.0.4240.75-enable-hardware-accelerated-mjpeg.patch) )

**Comment by refi64** [comment]
Our current patch already is slimmed down from the original due to the upstream changes already in stable, and I believe it should already cover the last two Fedora patches mentioned (the first one is useless since we build with Clang). That's not to say it couldn't be slimmed down *more*, since I accidentally formatted the file which added some extra changes, but I wouldn't consider it obsolete as-is.

**Comment by Esokrates** [comment]
Thanks guys for the awesome work. However, sadly I can't get VAAPI working here (worked previously with the Ubuntu PPA on my hardware). I installed the latest flatpak, enabled hardware accelerated decode and override software rendering list. Then I tried to play a 4k youtube video and in media-internals it says vpx video decoder and cpu usage is really high (and it's not due to vp9, this is supported on my intel kabylake gpu).

Any things I could try to help tracking this down? Sry for commenting here, probably a separate bug would be more appropriate, but on the other hand this one is for VAAPI anyway.

**Comment by Esokrates** [comment]
Related error messages:
```
[40:40:1213/212232.027944:ERROR:sandbox_linux.cc(382)] InitializeSandbox() called with multiple threads in process gpu-process.
Failed to load cookie file from cookie: Operation not permitted
Failed to load cookie file from cookie: Operation not permitted
[40:40:1213/212239.792039:ERROR:vaapi_wrapper.cc(1913)] vaPutSurface failed, VA error: the requested function is not implemented
[40:40:1213/212239.792333:ERROR:vaapi_video_decode_accelerator.cc(292)] Failed putting surface into pixmap
[115:66:1213/212239.793376:ERROR:batching_media_log.cc(38)] MediaEvent: {"error":"VDA Error 4"}
[40:40:1213/212248.520911:ERROR:vaapi_wrapper.cc(1913)] vaPutSurface failed, VA error: the requested function is not implemented
[40:40:1213/212248.521125:ERROR:vaapi_video_decode_accelerator.cc(292)] Failed putting surface into pixmap
[115:66:1213/212248.521420:ERROR:batching_media_log.cc(38)] MediaEvent: {"error":"VDA Error 4"}
Failed to load cookie file from cookie: Operation not permitted
[40:40:1213/212305.366732:ERROR:vaapi_wrapper.cc(1913)] vaPutSurface failed, VA error: the requested function is not implemented
[40:40:1213/212305.370337:ERROR:vaapi_video_decode_accelerator.cc(292)] Failed putting surface into pixmap
[115:66:1213/212305.371747:ERROR:batching_media_log.cc(38)] MediaEvent: {"error":"VDA Error 4"}
```

**Comment by Erick555** [comment]
Could you install `org.freedesktop.Platform.VaInfo` and show output from `flatpak run org.freedesktop.Platform.VaInfo`?

**Comment by Esokrates** [comment]
@Erick555 Here we go:
```
user@pc:~$ flatpak run org.freedesktop.Platform.VaInfo
libva info: VA-API version 1.7.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/intel-vaapi-driver/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_7
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.7 (libva 2.5.0)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 20.1.1 ()
vainfo: Supported profile and entrypoints
      VAProfileNone                   :	VAEntrypointVideoProc
      VAProfileNone                   :	VAEntrypointStats
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Simple            :	VAEntrypointEncSlice
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointFEI
      VAProfileH264Main               :	VAEntrypointEncSliceLP
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSlice
      VAProfileH264High               :	VAEntrypointFEI
      VAProfileH264High               :	VAEntrypointEncSliceLP
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileJPEGBaseline           :	VAEntrypointVLD
      VAProfileJPEGBaseline           :	VAEntrypointEncPicture
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline:	VAEntrypointFEI
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSliceLP
      VAProfileVP8Version0_3          :	VAEntrypointVLD
      VAProfileVP8Version0_3          :	VAEntrypointEncSlice
      VAProfileHEVCMain               :	VAEntrypointVLD
      VAProfileHEVCMain               :	VAEntrypointEncSlice
      VAProfileHEVCMain               :	VAEntrypointFEI
      VAProfileHEVCMain10             :	VAEntrypointVLD
      VAProfileHEVCMain10             :	VAEntrypointEncSlice
      VAProfileVP9Profile0            :	VAEntrypointVLD
      VAProfileVP9Profile2            :	VAEntrypointVLD
```

**Comment by Esokrates** [comment]
Still an issue withe the latest update of the chromium flatpak. Any suggestions what I could try? Does it work for you guys?

**Comment by Erick555** [comment]
Can you test with `flatpak run --env=LIBVA_DRIVER_NAME=i965 org.chromium.Chromium`?

**Comment by Esokrates** [comment]
@Erick555 Same issue:
```
user@pc:~$ flatpak run --env=LIBVA_DRIVER_NAME=i965 org.chromium.Chromium
Gtk-Message: 22:28:16.727: Failed to load module "canberra-gtk-module"
Gtk-Message: 22:28:16.728: Failed to load module "canberra-gtk-module"
[40:40:1229/222816.939576:ERROR:sandbox_linux.cc(382)] InitializeSandbox() called with multiple threads in process gpu-process.
Failed to load cookie file from cookie: Operation not permitted
Failed to load cookie file from cookie: Operation not permitted
[40:40:1229/222827.714270:ERROR:vaapi_wrapper.cc(1913)] vaPutSurface failed, VA error: the requested function is not implemented
[40:40:1229/222827.714514:ERROR:vaapi_video_decode_accelerator.cc(292)] Failed putting surface into pixmap
[118:88:1229/222827.722419:ERROR:batching_media_log.cc(38)] MediaEvent: {"error":"VDA Error 4"}
```

**Comment by BrozzSama** [comment]
I tested this on Intel Haswell and it works great for H264 videos. Just a quick note, Vulkan needs to be **DISABLED** on this specific platform, otherwise it will only show a white box instead of the decoded video, since Vulkan support is incomplete on Haswell. Maybe we can either have a workaround for it or at least a warning?

**Comment by Esokrates** [comment]
@refi64 The latest update broke vaapi completely, upon launching I get:
```
libva error: /usr/lib/x86_64-linux-gnu/dri/intel-vaapi-driver/i965_drv_video.so init failed
```
This path looks wrong, it should actually be
```
/usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
```

**Comment by refi64** [comment]
Did you install it from the linked PR or the normal Flathub beta repo? The
new builds haven't been published yet to the latter, so any errors would be
coincidental...

**Comment by refi64** [comment]
(ignore that, I was looking on the beta repo instead of stable...)

**Comment by refi64** [comment]
@Esokrates have you tried doing a full Flatpak update? That path is indeed the driver location at least on my system

```
$ flatpak run --command=bash org.chromium.Chromium//stable
[📦 org.chromium.Chromium src]$ ls /usr/lib/x86_64-linux-gnu/dri/intel-vaapi-driver/
etc  i965_drv_video.so	iHD_drv_video.so  lib
[📦 org.chromium.Chromium src]$ 
```

Could you do

```
flatpak info -c org.freedesktop.Platform//20.08
flatpak info -c org.freedesktop.Platform.VAAPI.Intel//20.08
```

and show the output of both commands?
