### ISSUE TITLE
Unable to use system proxy settings

### ISSUE THREAD

**Issue by laolux** [flathub/org.chromium.Chromium#36]
I just installed the chromium flatpak and cannot change the proxy settings.
Opening "settings -> advanced -> Open your computer's proxy settings" does open a new tab which reads

    When running Chromium under a supported desktop environment, the system proxy settings will be used. However, either your system is not supported or there was a problem launching your system configuration.

    But you can still configure via the command line. Please see man chrome for more information on flags and environment variables.

I suppose some permission is missing.

Info about my system: Fedora 33, kernel 5.9.12, flatpak 1.8.3

EDIT: specifying the correct proxy on the command line when starting chromium works:

    flatpak run org.chromium.Chromium --proxy-server=<address:port>

**Comment by andrunko** [comment]
Just to clarify, does chrome respects the settings if you configure via GNOME control center?

As for opening the settings UI from chrome settings, I did a quick check and this is done on `chrome/browser/ui/webui/settings_utils_linux.cc` which launches a system command depending on the environment it is running (GNOME, KDE, etc), so we probably need to special case here when running under flatpak sandbox to run the commands to open the settings via `flatpak-spawn --host` or something similar.

**Comment by wjt** [comment]
https://flatpak.github.io/xdg-desktop-portal/portal-docs.html#gdbus-org.freedesktop.portal.ProxyResolver there is a portal and glib knows how to use it

**Comment by andrunko** [comment]
Yes, but afaics the portal doesn't handle opening the system settings (maybe it should?), and chromium launches the configuration by calling the executables directly. I would be interested to know if chromium actually respects the settings configured though.

**Comment by laolux** [comment]
> Just to clarify, does chromium respects the settings if you configure via GNOME control center?

No, it completely ignores the proxy settings. Using a locally installed chromium works out of the box, so it must be the flatpak that is ignoring the settings from the GNOME control center.

> As for opening the settings UI from chromium settings, I did a quick check and this is done on `chrome/browser/ui/webui/settings_utils_linux.cc` which launches a system command depending on the environment it is running (GNOME, KDE, etc), so we probably need to special case here when running under flatpak sandbox to run the commands to open the settings via `flatpak-spawn --host` or something similar.

yes, when I try to open the proxy settings I get a warning message in my terminal window:

    [2:2:1208/123458.525340:ERROR:settings_utils_linux.cc(54)] Could not find GNOME network settings in $PATH

**Comment by andrunko** [comment]
Thanks @laolux, I am looking at some options here. Looks like we will need to implement support for the ProxyResolver portal as noted by @wjt above.

**Comment by refi64** [comment]
To be clear, there are two issues here:

1. Proxies not working
2. Opening the proxy settings not working

The portal support mentioned above fixes the first but not the second. I'd imagine we could probably just open GNOME Settings over D-Bus to avoid adding the host execute permission, since the proxy settings are available through the search provider interface, but I'm not sure about KDE.

**Comment by andrunko** [comment]
Yes, for 2) I thought that we could even consider removing the button/link from the settings (and maybe replace it with just an info text), but interesting idea for launching via D-Bus, will have a think.

**Comment by laolux** [comment]
Thanks for taking care of this issue.

For 2), please do not remove the link, that could be confusing. Instead, simply replace the text. Currently, when I click on that link "Open your computer's proxy settings" a new tab opens with the text in my first post. I think adjusting that text would be good. Something along the lines:

    The flatpak version of Chromium does not support changing the system proxy settings. However, it does respect those settings.
    So, if you need to adjust the proxy settings, please do so through the configuration system of your desktop environment.
    
    You can override your system proxy settings via the command line. Please see man chrome for more information on flags and environment variables.

**Comment by andrunko** [comment]
> Thanks for taking care of this issue.
> 
> For 2), please do not remove the link, that could be confusing. Instead, simply replace the text. Currently, when I click on that link "Open your computer's proxy settings" a new tab opens with the text in my first post. I think adjusting that text would be good. Something along the lines:
> 
> ```
> The flatpak version of Chromium does not support changing the system proxy settings. However, it does respect those settings.
> So, if you need to adjust the proxy settings, please do so through the configuration system of your desktop environment.
> 
> You can override your system proxy settings via the command line. Please see man chrome for more information on flags and environment variables.
> ```

**Comment by andrunko** [comment]
> Thanks for taking care of this issue.
> 
> For 2), please do not remove the link, that could be confusing. Instead, simply replace the text. Currently, when I click on that link "Open your computer's proxy settings" a new tab opens with the text in my first post. I think adjusting that text would be good. Something along the lines:
> 
> ```
> The flatpak version of Chromium does not support changing the system proxy settings. However, it does respect those settings.
> So, if you need to adjust the proxy settings, please do so through the configuration system of your desktop environment.
> 
> You can override your system proxy settings via the command line. Please see man chrome for more information on flags and environment variables.
> ```

@laolux Pushed a PR at https://github.com/flathub/org.chromium.Chromium/pull/41 and went with a similar text as you suggested. Would be good if you could try it and let us know of any issue.

**Comment by laolux** [comment]
Works great! Also changing the proxy settings works without having to restart chromium.
Thanks a lot!
