### ISSUE TITLE
Default to Wayland if given Wayland socket permission

### ISSUE THREAD

**Issue by thatLeaflet** [flathub/org.chromium.Chromium#361]
If Chromium is given the wayland socket permission, it should automatically use ozone=wayland. Currently, to use Wayland you either need to go to chrome://flags and set ozone.

This is how the Discord flatpak operates, and [this commit](https://github.com/flathub/com.discordapp.Discord/commit/a2f7a449af1af18a36e2547a2658cf5be5e986d5) shows how they did it.

**Comment by Erick555** [comment]
If chromium doesn't do this by default then flatpak shouldn't alter it.

**Comment by thalesmaoanz** [comment]
Sorry to ask here, but this is the reason why I can't share my screen using teams, meets or what-so-ever using chromium flatpak? I always get a black screen.
