### ISSUE TITLE
Add .pki as a persistent folder location

### ISSUE THREAD

**Issue by thatLeaflet** [flathub/org.chromium.Chromium#363]
By default, the Chromium flatpak has access to the whole home directory. One of the annoying things that Chromium does is create a .pki folder directly in the user's ~, which at no point the user will ever need to see.

By adding the .pki folder as a persistent folder location, this folder will instead be placed in ~/.var/app/org.chromium.Chromium/.pki so that the user will never has to see it.

**Comment by refi64** [comment]
Yup that won't actually work. If you want to avoid the .pki you can just remove the home permission. (It's only really there for compat reasons; this Flatpak predates the ability to open folders via the filesystem portal.)
