### ISSUE TITLE
Add support for policies

### ISSUE THREAD

**Issue by tpopela** [flathub/org.chromium.Chromium#37]
Would it be possible to add support for host policies? i.e. by adapting and backporting https://github.com/flathub/com.google.Chrome/commit/7aeccece837f6a838f9eba6001cda8a8ef06db16

**Comment by Erick555** [comment]
Support for host policies should come through extension: 

https://github.com/flathub/org.chromium.Chromium/blob/master/org.chromium.Chromium.yaml#L50

https://github.com/flathub/org.chromium.Chromium/issues/2

**Comment by wjt** [comment]
@andrunko perhaps we can document how this extension point is to be used in the README?

**Comment by tpopela** [comment]
Ah, sorry, this was not obvious to me. I think that it would be worth mentioning it somewhere. Also what isn't obvious to me as how to install it `flatpak install flathub org.chromium.Chromium.Policy` ends with `error: Nothing matches org.chromium.Chromium.Policy in remote flathub`

**Comment by Erick555** [comment]
I think it may be not tested/finished yet.

**Comment by refi64** [comment]
The idea is that you'd create a Flatpak extension with your policy, and it
would get picked up by Chromium while running. There aren't any public
demos of this atm, I have one locally I used for testing and could upload
it some time tomorrow.

**Comment by tpopela** [comment]
Ok, this is definitely not what I've expected. How these extension will be shipped by organizations or linux distributions? We in Fedora are actually preinstalling policies so people can easily access our infrastructure/forums/anything with their FAS account - see https://src.fedoraproject.org/rpms/fedora-chromium-config/tree/master. I would expect that whatever policy is in a predefined (by Chromium/Chrome) location on the host, then it will always be used by Chromium no matter from what origin it came.

**Comment by Erick555** [comment]
I'm afraid your expectations were wrong then because neither snap or flatpak will use your policy (I don't know which origins will, except fedora own chromium package).

Generally flatpaks don't share or pull any configs from host as you can't guarantee any compatibility between host and sandbox. Moreover various distros put those policies in different places like `/etc/chromium` or `/etc/chromium-browser` which complicates supporting host policies.

The extension mechanism was specifically crafted for distros/organizations to make use of them in flatpak friendly way.

**Comment by tpopela** [comment]
> I'm afraid your expectations were wrong then because neither snap or flatpak will use your policy (I don't know which origins will, except fedora own chromium package).

It will be used by https://github.com/flathub/com.google.Chrome, official packages of Chrome, Chromium from Fedora/RPM fusion, ..

> 
> Generally flatpaks don't share or pull any configs from host as you can't guarantee any compatibility between host and sandbox. Moreover various distros put those policies in different places like `/etc/chromium` or `/etc/chromium-browser` which complicates supporting host policies.

I don't know, but Chromium itself guarantees the compatibility there (and you can observe the current state through chrome://policy). The chromium vs. chromium-browser actually was actually started by us in Fedora, but we later moved to chromium (and I think that other followed).

> The extension mechanism was specifically crafted for distros/organizations to make use of them in flatpak friendly way.

I'm not disputing the current implementation, but I'm just trying to wrap my head around. If it will be super easy to build the extension (would be nice if it would be without any tooling, as in the end the policy is just a JSON file) and also figure out the way how to host it somewhere (What the workflow would be there? Do you expect that distributions/organizations will run their own Flatpak remote?).

**Comment by Erick555** [comment]
> It will be used by https://github.com/flathub/com.google.Chrome, official packages of Chrome, Chromium from Fedora/RPM fusion

Yes flathub chrome may use it but only because it's doesn't come from source that can be patched. The price for this is exposing whole `/etc` in sandbox.

> The chromium vs. chromium-browser actually was actually started by us in Fedora, but we later moved to chromium (and I think that other followed).

They didn't. Debian/Ubuntu still use `chromium-browser` and it's the only thing that snap honors.

I hope publishing the demo and adding some docs will make things clearer about what is needed to do here.

**Comment by andrunko** [comment]
I pushed #38 as an attempt to document how this works. Not very inspired today but hope it helps.
