### ISSUE TITLE
Can't watch Netflix after recent updates to Mesa?

### ISSUE THREAD

**Issue by regulator-g** [flathub/org.chromium.Chromium#377]
hi guys,
I cant watch netflix after a doing recent flatpak updates, Chromium flatpak hasnt been updated for a week so I don't think its a chromium issue, i actually think it was an update to flatpak Mesa VA-API or Openh264 that broke it? 

Twitch and Youtube are working so it may also be realted to DRM?

Fedora 39
Gnome 45.5
intel cpu/igpu
Mesa 23.08

Flatpak list of mesa and intel:
```

Mesa                                              org.freedesktop.Platform.GL.default                             24.0.3                            22.08                   flathub             system
Mesa (Extra)                                      org.freedesktop.Platform.GL.default                             24.0.3                            22.08-extra             flathub             system
Mesa                                              org.freedesktop.Platform.GL.default                             24.0.3                            23.08                   flathub             system
Mesa (Extra)                                      org.freedesktop.Platform.GL.default                             24.0.3                            23.08-extra             flathub             system
Intel                                             org.freedesktop.Platform.VAAPI.Intel                                                              22.08                   flathub             system
Intel                                             org.freedesktop.Platform.VAAPI.Intel                                                              23.08                   flathub             system
openh264                                          org.freedesktop.Platform.openh264                               2.1.0                             2.2.0                   flathub             system

```

media internals:
render_id: 9
player_id: 1
created: 2024-03-21 00:47:50.068958 UTC
origin_url: https://www.netflix.com/
kFrameUrl: https://www.netflix.com/browse
kFrameTitle: Home - Netflix
url: blob:https://www.netflix.com/2286b5f0-0565-4463-adb8-c9a41d20de3a
info: ChunkDemuxer
kRendererName: RendererImpl
pipeline_state: kStarting

{
  "properties": {
    "render_id": 9,
    "player_id": 1,
    "created": "2024-03-21 00:47:50.068958 UTC",
    "origin_url": "https://www.netflix.com/",
    "kFrameUrl": "https://www.netflix.com/browse",
    "kFrameTitle": "Home - Netflix",
    "url": "blob:https://www.netflix.com/2286b5f0-0565-4463-adb8-c9a41d20de3a",
    "info": "ChunkDemuxer",
    "kRendererName": "RendererImpl",
    "pipeline_state": "kStarting"
  },
  "events": [
    {
      "time": 0,
      "key": "created",
      "value": "2024-03-21 00:47:50.068958 UTC"
    },
    {
      "time": 0.12800000002607703,
      "key": "origin_url",
      "value": "https://www.netflix.com/"
    },
    {
      "time": 0.13200000001234002,
      "key": "kFrameUrl",
      "value": "https://www.netflix.com/browse"
    },
    {
      "time": 0.13500000000931323,
      "key": "kFrameTitle",
      "value": "Home - Netflix"
    },
    {
      "time": 0.22100000001955777,
      "key": "url",
      "value": "blob:https://www.netflix.com/2286b5f0-0565-4463-adb8-c9a41d20de3a"
    },
    {
      "time": 0.26800000001094304,
      "key": "info",
      "value": "ChunkDemuxer"
    },
    {
      "time": 0.27700000000186265,
      "key": "kRendererName",
      "value": "RendererImpl"
    },
    {
      "time": 0.3000000000174623,
      "key": "pipeline_state",
      "value": "kStarting"
    }
  ]
}

happy to provide more logs or report this further upstream just tell me what to do :)

**Comment by refi64** [comment]
My immediate guess would be a widevine issue but I'm not intimately familiar with the details of netflix video playback. Does it work in e.g. flatpak brave/chrome or their desktop versions?

**Comment by regulator-g** [comment]
thanks for the reply, tried chrome and chromium and worked out it was caused by an extension! I had a "netflix 1080p" extension as people said netflix on linux is capped at 720 but i guess they block people using the extension

https://chromewebstore.google.com/detail/netflix-1080p/cankofcoohmbhfpcemhmaaeennfbnmgp
