### ISSUE TITLE
Native wayland Chromium broken after latest update

### ISSUE THREAD

**Issue by pizzadude** [flathub/org.chromium.Chromium#385]
On Fedora 40 KDE, the latest update to the Chromium flatpak broke native wayland, it just launches a transparent window where my cursor trails everywhere like the old Windows XP days. I had to switch the "ozone" back to default in another chromium build and copy my config back.

```
CPU:    Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz
        4 cores/threads
        3500.00 MHz
GPU:    Mesa Intel(R) HD Graphics 620 (KBL GT2)
        OpenGL 4.6 (Compatibility Profile) Mesa 24.0.5
        GLSL 4.60
```

**Comment by regulator-g** [comment]
same issue on Fedora 39 using flatpak image, rolled back to previous version:

`sudo flatpak update --commit=d8cc53624b3a8569d93af57ff587bfdb316cf295802a7ea5374fea22ac3ba2fc org.chromium.Chromium`

**Comment by refi64** [comment]
This is an [upstream bug](https://issues.chromium.org/issues/329678163) and specifically applies if you set the "Preferred Ozone platform" / `ozone-platform-hint` option. You should be able to run Chromium with `--ozone-platform=wayland` to work around it.
