### ISSUE TITLE
Fix lack of sound

### ISSUE THREAD

**Issue by refi64** [flathub/org.chromium.Chromium#4]
Can't connect to the pulse socket...

**Comment by analotia** [comment]
I have the exact same problem on my ungoogled-chromium flatpak. This 
only happens when you use system libraries, right?

**Comment by refi64** [comment]
No, I'm using the bundled libraries now, and it still occurs.

**Comment by analotia** [comment]
What changes did you make? I recall it was working fine with the older 
build...

**Comment by refi64** [comment]
No idea 😅 at least I'm not aware of what would have caused this, outside of breaking accidentally due to a tangentially related upstream change

**Comment by refi64** [comment]
Already fixed

**Comment by felipeborges** [comment]
I just got Chromium 87.0.4280.88 and it has no audio.

```
flatpak info org.chromium.Chromium

Chromium Web Browser - The web browser from Chromium project

          ID: org.chromium.Chromium
         Ref: app/org.chromium.Chromium/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 87.0.4280.88
     License: BSD-3-Clause and LGPL-2.1+ and Apache-2.0 and IJG and MIT and GPL-2.0+ and ISC and OpenSSL and (MPL-1.1 or GPL-2.0 or LGPL-2.0)
      Origin: flathub
  Collection: org.flathub.Stable
Installation: user
   Installed: 266.1 MB
     Runtime: org.freedesktop.Platform/x86_64/20.08
         Sdk: org.freedesktop.Sdk/x86_64/20.08

      Commit: 4adfba59d8a3ab6b7bcee2d0981649a9087380535271eb3ddc9b4575b32bcadb
     Subject: Update Chromium to 87.0.4280.88 (8b296ce1)
        Date: 2020-12-04 21:25:57 +0000
```

Same when I got it from flathub-beta.

**Comment by cho2** [comment]
> I just got Chromium 87.0.4280.88 and it has no audio.

It has audio here, 87.0.4280.88 also.

**Comment by refi64** [comment]
@felipeborges any particular errors in the console?

**Comment by felipeborges** [comment]
> @felipeborges any particular errors in the console?

nothing obvious, so I ran it with `--enable-logging=stderr --v=1` [chromium-log.txt](https://github.com/flathub/org.chromium.Chromium/files/5694904/chromium-log.txt)

I tested on youtube and vimeo.

**Comment by felipeborges** [comment]
I didn't bisect which update did it, but it is now fixed for me. Thank you!
