### ISSUE TITLE
Verify the Flatpak

### ISSUE THREAD

**Issue by AsciiWolf** [flathub/org.chromium.Chromium#437]
Considering how large the Chromium Flatpak user base is, I think it would be very beneficial to [verify](https://docs.flathub.org/docs/for-app-authors/verification) this Flatpak. If possible, please consider working with the Chromium team on this.

**Comment by Erick555** [comment]
Chromium team is not involved in this flatpak. Moreover the only official Chromium build is Chrome. I don't think there is any possibility Chromium team can endorse 3rd party build they aren't involved with.
