### ISSUE TITLE
I cannot access the other partitions

### ISSUE THREAD

**Issue by legallyfree** [flathub/org.chromium.Chromium#46]
Hello, I cannot access the other partitions, 
my partitions that are mounted in 
run/media/my_user/name_partition 
do not show me the media folder where my partitions are mounted, 
when I visualize the run folder it only shows 6 folders -> cups, dbus, flatpak, host, systemd, user, and I don't see the media folder where the mounted partitions are, and in the dolpin I can see the 32 folders that the run folder actually has, 

could you tell me how to fix it or do you need to wait for a patch?

**Comment by refi64** [comment]
Try editing your permissions to include --filesystem=/run/media (via
`flatpak override` or Flatseal).
