### ISSUE TITLE
vaInitialize failed using DRM: unknown libva error

### ISSUE THREAD

**Issue by fishxz** [flathub/org.chromium.Chromium#5]
![image](https://user-images.githubusercontent.com/1385258/96296977-72f29400-0ff0-11eb-9d2a-b58286a33e5b.png)
![image](https://user-images.githubusercontent.com/1385258/96297004-81d94680-0ff0-11eb-87d0-ffbfacd43b5b.png)

gpu: amd rx580

**Comment by refi64** [comment]
Are you using Wayland or Xorg? VA-API is not supported on Wayland for now (not sure if Ozone will be bringing this).

**Comment by fishxz** [comment]
im on wayland, but i get the same error on xorg.

**Comment by refi64** [comment]
Hmm, I'll check it out. Btw due to upstream changes until Chromium 87 or
88, you have to start it with --use-gl=desktop for VA-API to work. Have you
tried that?

**Comment by fishxz** [comment]
![image](https://user-images.githubusercontent.com/1385258/96336000-c4486500-107c-11eb-9f1e-285c910e8a1c.png)

but `chrome://media-internals/` shows

![image](https://user-images.githubusercontent.com/1385258/96336012-d5917180-107c-11eb-838e-8519a371a4a2.png)

**Comment by refi64** [comment]
Sounds like everything is fine here.
