### ISSUE TITLE
Launch with --proxy-server option

### ISSUE THREAD

**Issue by gaetanars** [flathub/org.chromium.Chromium#60]
I don't find how to launch flatpack Chromium with proxy-server directive. I try to copy `.local/share/flatpak/exports/share/applications/org.chromium.Chromium.desktop` in `.local/share/applications/` and edit command to add `--proxy-server=192.168.2.2:3128`, but it didn't work.

Can you please help?

**Comment by gaetanars** [comment]
After launch, and re-launch it seems to work now with `--proxy-server="192.168.2.2:3128"`

**Comment by refi64** [comment]
You can also add custom flags to `~/.var/app/org.chromium.Chromium/config/chromium-flags.conf` (one flag per line) instead of editing the .desktop file.

**Comment by gaetanars** [comment]
Thanks
