### ISSUE TITLE
Flatpak minimum version

### ISSUE THREAD

**Issue by bluewww** [flathub/org.chromium.Chromium#62]
I'm working with a centos7 box that has flatpak with the version `1.0.9`.
I see that `org.chromium.Chromium` needs at least `1.8.2`. What is the reason for this? Is there a way for me to lower the requirements (by dropping some features)?

**Comment by Erick555** [comment]
Unfortunately it's not possible to lower requirements. 1.8.2 is the oldest version that can run chromium at all.

**Comment by refi64** [comment]
Yeah this basically depends on bug fixes & added features in 1.8.2. You could try building a newer Flatpak manually...
