### ISSUE TITLE
Failed to run chromium due to `gdbus call` error

### ISSUE THREAD

**Issue by bitphage** [flathub/org.chromium.Chromium#66]
I've tried to run chromium and got an error from `portal_error.txt`, then I've checked that my kernel settings are ok, and then debugged it further, and found that `chromium.sh` has a `gdbus` call which is not working for me:

```
$ flatpak run --command=bash org.chromium.Chromium
$ gdbus call -e -d org.freedesktop.portal.Flatpak -o /org/freedesktop/portal/Flatpak -m org.freedesktop.DBus.Properties.Get org.freedesktop.portal.Flatpak version
Error connecting: Failed to execute child process “dbus-launch” (No such file or directory)
```

Same command from host systems runs fine:

```
% gdbus call -e -d org.freedesktop.portal.Flatpak -o /org/freedesktop/portal/Flatpak -m org.freedesktop.DBus.Properties.Get org.freedesktop.portal.Flatpak version
(<uint32 4>,)
```

**Comment by bitphage** [comment]
It works if launch with explicit dbus session like `dbus-launch flatpak run org.chromium.Chromium`

**Comment by refi64** [comment]
You definitely need a session bus running in order to use Flatpaks well in general, I'd imagine there's just not one running in this case, or it's not being picked up (which would be a Flatpak issue).

This isn't something we can control from over here.
