### ISSUE TITLE
Wrong directories for policies and native-messaging-hosts

### ISSUE THREAD

**Issue by iavael** [flathub/org.chromium.Chromium#78]
Extension point definition merges directories with policies to /app/chromium/policies/policies/managed/ and /app/chromium/policies/policies/recommended/
While chromium actually looks for policies at paths /app/chromium/policies/managed/ and /app/chromium/policies/recommended/
```
[pid 730559] openat(AT_FDCWD, "/app/chromium/policies/managed", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = -1 ENOENT (No such file or directory)
[pid 730559] openat(AT_FDCWD, "/app/chromium/policies/recommended", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = -1 ENOENT (No such file or directory)
```

Same goes for native-messaging-hosts: /app/chromium/native-messaging-hosts/native-messaging-hosts/

**Comment by gasinvein** [comment]
Oh, this explains why kerberos auth stopped working for me after some update.

**Comment by gasinvein** [comment]
I guess it was [this](https://github.com/flathub/org.chromium.Chromium/commit/9c892f32b40d870cefcd4a028c0c703db72a5c32#diff-5b52aeb1e04e809e6726675fb35d4aa77ef176390da956f13ab9df250da93aa4L76-R76) change, policies path in the patch changed from `/app/chromium/policies/policies` to `/app/chromium/policies`.

**Comment by gasinvein** [comment]
This should be now fixed by #92

**Comment by shrublet** [comment]
Sorry to necro this, but policies still only load for me at `chromium/policies/policies` with the managed and recommended sub-directories (i.e. `~/.local/share/flatpak/app/org.chromium.Chromium/current/active/files/chromium/policies/policies`). Is this intended? Thanks!

**Comment by iavael** [comment]
@shrublet 
"policies/policies" path is artifact of using org.chromium.Chromium.Policy extension interface, because of this configuration in chromium manifest
```
[Extension org.chromium.Chromium.Policy]
directory=chromium/policies
autodelete=true
no-autodownload=true
subdirectories=true
merge-dirs=policies/managed;policies/recommended
version=1
```
Basically, path fragments from `directory` and from `merge-dirs` are concatenated, and so you get `chromium/policies/policies/{managed,recommended}`

If you use org.chromium.Chromium.Extension extension interface, then your policy files would be put to `chromium/extensions/policies/{managed,recommended}` path because of this interface definition
```
[Extension org.chromium.Chromium.Extension]
directory=chromium/extensions
autodelete=true
no-autodownload=true
subdirectories=true
merge-dirs=extensions;native-messaging-hosts;policies/managed;policies/recommended
version=1
```

You can look extension interfaces for flatpak app by calling `flatpak info -m org.chromium.Chromium`
If `chromium/extensions/policies/{managed,recommended}` doesn't work for you, then open an issue in this repo

You also can read https://github.com/flathub/org.chromium.Chromium/commit/e863676f0ab66254a2982d733d0606dedd269a98 commit for details about org.chromium.Chromium.Extension interface superseding org.chromium.Chromium.Policy and org.chromium.Chromium.NativeMessagingHost
