### ISSUE TITLE
Calls on Skype Web do not work

### ISSUE THREAD

**Issue by Esokrates** [flathub/org.chromium.Chromium#80]
When going to https://web.skype.com/ and trying to call someone the call buttons are greyed out stating "Audio and video calls are not supported on your browser".
In Google Chrome it works just fine. The user agent also seems to match the latest Google Chrome binary.
Settings are all default.

Would be great if you could fix this!

**Comment by Esokrates** [comment]
Please consider adding the following patch proposed here:
https://github.com/Eloston/ungoogled-chromium/issues/1010#issuecomment-643740388

**Comment by refi64** [comment]
This is trying to stay relatively close to upstream with the exception of patches to improve Linux/Flatpak support.
