### ISSUE TITLE
Error calling Spawn(): org.freedesktop.DBus.Error.FileNotFound

### ISSUE THREAD

**Issue by rany2** [flathub/org.chromium.Chromium#81]
From @JoshuaFern  https://github.com/flathub/com.github.Eloston.UngoogledChromium/issues/21 : 

I use quite a few flatpak apps, but for some reason this one isn't working on NixOS.

```shell
nixos-workstation% flatpak run com.github.Eloston.UngoogledChromium
[2:17:0311/070342.906792:ERROR:flatpak_sandbox.cc(576)] Error calling Spawn(): org.freedesktop.DBus.Error.FileNotFound: Failed to start command: Failed to execute child process “flatpak” (No such file or directory)
nixos-workstation% flatpak --version
Flatpak 1.10.1
nixos-workstation% uname -a
Linux nixos-workstation 5.10.18 #1-NixOS SMP Tue Feb 23 14:53:25 UTC 2021 x86_64 GNU/Linux
nixos-workstation% cat /etc/os-release
NAME=NixOS
ID=nixos
VERSION="21.05pre273435.0aeba64fb26 (Okapi)"
VERSION_CODENAME=okapi
VERSION_ID="21.05pre273435.0aeba64fb26"
PRETTY_NAME="NixOS 21.05 (Okapi)"
LOGO="nix-snowflake"
HOME_URL="https://nixos.org/"
DOCUMENTATION_URL="https://nixos.org/learn.html"
SUPPORT_URL="https://nixos.org/community.html"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
```

Affects Chromium as well https://github.com/flathub/com.github.Eloston.UngoogledChromium/issues/21#issuecomment-797515642

**Comment by refi64** [comment]
If `flatpak run --command=flatpak-spawn com.github.Eloston.UngoogledChromium --sandbox echo 123` fails, then it's a NixOS packaging issue and not something we can resolve.

**Comment by JoshuaFern** [comment]
```
nixos-workstation% flatpak run --command=flatpak-spawn com.github.Eloston.UngoogledChromium --sandbox echo 123
Portal call failed: Failed to start command: Failed to execute child process “flatpak” (No such file or directory)
```

I'm a package maintainer for NixOS but not the Flatpak package in particular. I don't know enough about flatpak to understand what's going on here.

**Comment by Strahinja** [comment]
This is still happening for me after switching the repository URLs in Alpine Linux in _/etc/apk/repositories_ to `v3.19` from `v3.18`, upgrading the system and flatpak and rebooting.
