### ISSUE TITLE
"Open in window" shortcuts not treated as distinct apps by GNOME Shell

### ISSUE THREAD

**Issue by wjt** [flathub/org.chromium.Chromium#83]
With Chrome running outside Flatpak, if I go to *☰ → More tools → Create shortcut…* and check "Open as Window", then:

* I get a launcher in my app grid
* The website launches in its own window
* It behaves as an "app": it has its own icon in the GNOME Alt-Tab app switcher and dash (or taskbar on Endless OS)

See this screenshot: I created a MetaFilter shortcut in Chrome, and it has a little dot below it to show that it is running. Other Chrome windows are grouped with Chrome.

![Capture d’écran de 2021-03-17 12-29-59](https://user-images.githubusercontent.com/86760/111481385-cf3a1b00-872a-11eb-9f7d-d5ac2ecc43fb.png)

By contrast, if I do the same thing with this Chromium Flatpak, it's just lumped in with other Chrome windows. I pinned the MetaFilter launcher to the taskbar and clicking it launches the right window, but it's not associated with the MetaFilter launcher.

![Capture d’écran de 2021-03-17 12-30-52](https://user-images.githubusercontent.com/86760/111482966-491ed400-872c-11eb-8ce6-ce62b566316c.png)

I believe this is because GNOME Shell detects sandboxed apps and then requires their `.desktop` file ID to be prefixed with that ID. And in fact this code goes to great lengths to try to support Chrom(e,ium) shortcuts. https://gitlab.gnome.org/GNOME/gnome-shell/blob/ec071ae4c2c747cc432839805d0c3754f647d55a/src/shell-window-tracker.c#L132-215

But of course the `.desktop` files exported by the browser do not have filenames matching the prefix `org.chromium.Chromium.` so all this is defeated.

**Comment by wjt** [comment]
Not sure whether one can just rename the `.desktop` files…

**Comment by refi64** [comment]
Well by complete coincidence someone else had raised this issue and I couldn't figure out why, but it being the app ID prefix makes sense...I'm not aware of any particular reason we can't just rename it, the only trick would be automating the rename in flextop.
