### ISSUE TITLE
FIDO U2F and FIDO2 devices don't work

### ISSUE THREAD

**Issue by mb291** [flathub/org.chromium.Chromium#93]
Hello

FIDO U2F and FIDO2 devices don't work at all with current Chromium Flatpak 89.0.4389.128 on Debian 11 (Bullseye). 

Can this get enabled ?

Regards

**Comment by wjt** [comment]
Dup of #20

**Comment by mb291** [comment]
With the current build it works!

`Chromium W… The web browser from Chromium project  org.chromium.Chromium     92.0.4515.107 stable flathub
`

Great.
