### ISSUE TITLE
Minnor problem wrong version info

### ISSUE THREAD

**Issue by mb291** [flathub/org.chromium.Chromium#96]
The current flatpak list the wrong version number

`Chromium
Version **90.0.4430.72 (Official Build)** (64-bit)`

flatpak list gives:

`flatpak list
Name                               Application ID                     Version       Branch Installation
Flatseal                           com.github.tchx84.Flatseal         1.6.8         stable user
Metadata Cleaner                   fr.romainvigier.MetadataCleaner    1.0.5         stable user
**Chromium Web Browser               org.chromium.Chromium              89.0.4389.128 stable user**
Codecs                             org.chromium.Chromium.Codecs                     stable user
Freedesktop Platform               org.freedesktop.Platform           20.08.8       20.08  user
default                            …g.freedesktop.Platform.GL.default               20.08  user
Intel                              ….freedesktop.Platform.VAAPI.Intel              
........................`

**Comment by Erick555** [comment]
This is fixed in github but no published in flathub yet: https://github.com/flathub/org.chromium.Chromium/pull/95

**Comment by mb291** [comment]
OK - this means it will be accurate again in the next release ?

**Comment by Erick555** [comment]
yes

**Comment by wjt** [comment]
```
wjt@camille:~$ flatpak info org.chromium.Chromium                                                                                   

Chromium Web Browser - The web browser from Chromium project

          ID: org.chromium.Chromium
         Ref: app/org.chromium.Chromium/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 90.0.4430.85
     License: BSD-3-Clause and LGPL-2.1+ and Apache-2.0 and IJG and MIT and GPL-2.0+ and ISC and OpenSSL and (MPL-1.1 or GPL-2.0 or LGPL-2.0)
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 280.1 MB
     Runtime: org.freedesktop.Platform/x86_64/20.08
         Sdk: org.freedesktop.Sdk/x86_64/20.08

      Commit: 4a4dc3d2950317b68bf7ce6a9cb62bdd7426ab8b4af8f9d4e4c8667e8e676c12
      Parent: 42168195fbedf45a959a2a0c8860ea8b58ea5834669abee33111cdb41769d3df
     Subject: Update chromium-90.0.4430.72.tar.xz to 90.0.4430.85 (772ea2af)
        Date: 2021-04-21 05:36:32 +0000
```
